# For more information please see:
# http://wiki.ros.org/costmap_2d/hydro/obstacles
# http://wiki.ros.org/teb_local_planner/Tutorials/Obstacle%20Avoidance%20and%20Robot%20Footprint%20Model

obstacle_range: 1.5
raytrace_range: 2.0
footprint: [[0.17, 0.14], [-0.25, 0.14], [-0.25, -0.14],  [0.17, -0.14]]
inflation_radius: 0.50

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}