obstacle_range: 1.5  #todo default == 2.5
raytrace_range: 2.0  #todo default == 3.0
footprint: [[0.17, 0.14], [-0.25, 0.14], [-0.25, -0.14],  [0.17, -0.14]]
inflation_radius: 0.50  #todo default == 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}