obstacle_range: 2.5
raytrace_range: 3.0  #todo
footprint: [[0.14, 0.17], [0.14, -0.25], [-0.14, -0.25],  [-0.14, 0.17]]
inflation_radius: 0.55

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}