# For more information please see:
# http://wiki.ros.org/costmap_2d#costmap_2d.2Flayered.Parameters

global_costmap:
  global_frame: map
  robot_base_frame: camera_link
  update_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
