global_costmap:
  global_frame: /map   #todo
  robot_base_frame: camera_link
  update_frequency: 5.0
  static_map: true  #todo If you aren't using an existing map or map server, set the static_map parameter to false.