# For more information please see:
# http://wiki.ros.org/costmap_2d#costmap_2d.2Flayered.Parameters

local_costmap:
  global_frame: odom
  robot_base_frame: camera_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
